default: &default
  host: localhost
  user: postgres
  password: postgres
  adapter: postgres

development:
  <<: *default
  db: rickandmorty_api

test:
  <<: *default
  db: rickandmorty_api

production:
  <<: *default
  db: rickandmorty_api
